### ISSUE TITLE
Failed on skinparam

### ISSUE THREAD

**Issue by yaleh** [bafolts/plantuml-code-generator#5]
When processing a .plu like this:

    @startuml

    skinparam defaultFontSize 20

    hide empty members
    class Toyota
    @enduml

It shows an error msg:

    Error parsing input file:

**Comment by arwenvaughan** [comment]
Yep, this has been confirmed. Thanks for the input.

On Tue, Jan 13, 2015 at 9:36 AM, Yale Huang <notifications@github.com>
wrote:

> When processing a .plu like this:
>
> @startuml
>
> skinparam defaultFontSize 20
>
> hide empty members
> class Toyota
> @enduml
>
> It shows an error msg:
>
> Error parsing input file:
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bafolts/plantuml-code-generator/issues/5>.
>



-- 
Arwen

C: 832-326-9287
H: 303-261-8606
arwenvaughan@gmail.com

**Comment by bafolts** [comment]
I updated the error messaging so that on the next error we get more than the first line displayed to the user. I also updated the grammar to support "skinparam " lines. Since these lines are of no benefit to the generated UML, I just added them to the list of ignored lines.

https://github.com/bafolts/plantuml-code-generator/commit/c3914faca6cd2b2a80903e3a7668967d9fbc9d90
